home: /home/simon

supported_distros: 
  - Void

is_gui: true

packages:
  linux:
    - curl
    - fzf
    - jq
    - bottom
    - htop

  GUI:
    linux:
      - qutebrowser
      - river
      - Waybar
      - dunst


git:
  email: simon@simonhugh.xyz
  name: Simon H Moore
  username: simonhughxyz
  work:
    email: simon.moore@audiebant.co.uk
    name: Simon H Moore
    username: simonhughxyz
