home: /home/simon

supported_distros: 
  - Void

is_gui: true

packages:
  linux:
    - curl
    - fzf
    - jq
    - bottom
    - htop
    - aria2
    - neovim
    - pass
    - starship

  GUI:
    linux:
      - qutebrowser
      - river
      - Waybar
      - dunst
      - mpv
      - zathura
      - zathura-pdf-mupdf
      - zathura-ps


git:
  email: simon@simonhugh.xyz
  name: Simon H Moore
  username: simonhughxyz
  work:
    email: simon.moore@audiebant.co.uk
    name: Simon H Moore
    username: simonhughxyz
