---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ niri_packages }}"

- name: Create the '$HOME/.config/niri' directory if not exists
  ansible.builtin.file:
    path: "{{ home }}/.config/niri"
    mode: u=rwx,g=,o=
    state: directory

- name: Copy niri config
  ansible.builtin.copy:
    src: config.kdl
    dest: "{{ home }}/.config/niri/config.kdl"
    mode: u=rw,g=,o=
    force: yes
