---
- name: Create the '$HOME/.config/shell' directory if not exists
  ansible.builtin.file:
    path: "{{ home }}/.config/shell"
    mode: u=rwx,g=,o=
    state: directory

- name: Copy profile bootstrap file
  ansible.builtin.copy:
    src: ".profile"
    dest: "{{ home }}/.profile"
    mode: u=rwx,g=,o=
    force: yes

- name: Copy shell files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home }}/.config/shell/{{ item }}"
    mode: u=rwx,g=,o=
    force: yes
  loop:
    - .zprofile
    - .zshrc
    - alias.sh
    - alias.zsh
    - profile

- name: Ensure zplug is installed
  ansible.builtin.git:
    repo: https://github.com/zplug/zplug.git
    dest: "{{ home }}/.cache/shell/zplug"
    update: yes
