---
- name: Bootstrap system
  hosts: all
  tags: [bootstrap]
  tasks:
    - name: Create user
      ansible.builtin.include_role:
        name: user

- name: Configure user
  hosts: all
  vars:
    home: "/home/{{ user.name }}"
  tasks:
    - name: Apply user roles
      ansible.builtin.include_role:
        name: "{{ role_name }}"
        apply:
          become: true
          become_user: "{{ user.name }}"
          tags:
            - "{{ role_name }}"
      loop: "{{ user.roles | default([]) }}"
      loop_control:
        loop_var: role_name
        label: "{{ role_name }}"
      tags: [always]
