---
- name: Configure system
  hosts: all
  tasks:
    - name: Print the OS family
      ansible.builtin.debug:
        msg: "OS family is {{ ansible_facts['os_family'] }}"

    - name: Determine packages to install
      set_fact:
        packages_to_install: >-
          {{
            (packages.linux if ansible_facts['os_family'] in supported_distros else [])
            + (packages[ansible_facts['os_family']|lower] | default([]))
          }}

    - name: Determine GUI packages to install
      set_fact:
        packages_to_install: >-
          {{
            packages_to_install
            + (packages.GUI.linux if ansible_facts['os_family'] in supported_distros else [])
            + (packages.GUI[ansible_facts['os_family']|lower] | default([]))
          }}
      when: is_gui | default(false)

    - name: Install packages
      become: true
      ansible.builtin.package:
        name: "{{ packages_to_install }}"
        state: present
        update_cache: yes


    - name: Install shell config
      include_role:
        name: shell

    - name: Install git config
      include_role:
        name: git

    - name: Install Neovim config
      include_role:
        name: nvim

    - name: Install password-store
      include_role:
        name: password-store

    - name: Install fontconfig config
      include_role:
        name: fontconfig

    - name: Install aria2 config
      include_role:
        name: aria2

    - name: Install river config
      include_role:
        name: river
      when: ansible_facts['os_family'] in supported_distros and is_gui

    - name: Install waybar config
      include_role:
        name: waybar
      when: ansible_facts['os_family'] in supported_distros and is_gui

    - name: Install dunst config
      include_role:
        name: dunst
      when: ansible_facts['os_family'] in supported_distros and is_gui

    - name: Install zathura config
      include_role:
        name: zathura
      when: ansible_facts['os_family'] in supported_distros and is_gui

    - name: Install mpv config
      include_role:
        name: mpv
      when: ansible_facts['os_family'] in supported_distros and is_gui
