---
- name: Bootstrap system
  hosts: all
  tags: [bootstrap]
  tasks:
    - name: Print the OS family
      ansible.builtin.debug:
        msg: "OS family is {{ ansible_facts['os_family'] }}"

    - name: Create user
      ansible.builtin.include_role:
        name: user

- name: Configure user
  hosts: all
  vars:
    home: "/home/{{ user.name }}"
  tasks:
    - name: Apply user roles
      ansible.builtin.include_role:
        name: "{{ role_name }}"
        apply:
          become: true
          become_user: "{{ user.name }}"
          tags:
            - "{{ role_name }}"
      loop: "{{ user.roles | default([]) }}"
      loop_control:
        loop_var: role_name
        label: "{{ role_name }}"
      tags: [always]

- name: Configure system
  hosts: all
  vars:
    home: "/home/{{ user.name }}"
  tasks:
    - name: Install niri config
      ansible.builtin.include_role:
        name: niri
      when: is_gui
      tags: [system, gui, niri]

    - name: Install waybar config
      ansible.builtin.include_role:
        name: waybar
      when: is_gui
      tags: [system, gui, waybar]

    - name: Install dunst config
      ansible.builtin.include_role:
        name: dunst
      when: is_gui
      tags: [system, gui, dunst]

    - name: Install zathura config
      ansible.builtin.include_role:
        name: zathura
      when: is_gui
      tags: [system, gui, zathura]

    - name: Install mpv config
      ansible.builtin.include_role:
        name: mpv
      when: is_gui
      tags: [system, gui, mpv]

    - name: Install autofs config
      ansible.builtin.include_role:
        name: autofs
      tags: [system, autofs]
