#!/bin/sh
# 
# Simon H Moore <simon@simonhugh.xyz>
#
# Preview handler for lf
# https://github.com/gokcehan/lf/wiki/Previews

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

image() {
  # Check for WSL
  if [ -f "/proc/sys/fs/binfmt_misc/WSLInterop" ]; then
    # Check for windows terminal
    # it does not support sixel yet, see https://github.com/microsoft/terminal/issues/448
    if [ "$(cmd.exe /c echo %WT_SESSION% 2> /dev/null)" != "%WT_SESSION%" ];then
      chafa "$1" --polite on -s "$(($2-2))x$3" | sed 's/#/\n#/g'
      exit 0
    fi
  fi
  chafa "$1" --polite on -f sixel -s "$(($2-2))x$3" | sed 's/#/\n#/g'
  exit 0
}

# Note that the cache file name is a function of file information, meaning if
# an image appears in multiple places across the machine, it will not have to
# be regenerated once seen.

export BAT_CONFIG_PATH="$XDG_CONFIG_HOME/lf/bat.config"

case "$(file --dereference --brief --mime-type -- "$1")" in
  image/*) image "$1" "$2" "$3" "$4" "$5" ;;
  text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1"  ;;
  text/troff) man ./ "$1" | col -b ;;
  text/* | */xml | application/json) bat --terminal-width "$4" "$1" ;;
  application/zip | application/gzip) atool --list -- "$1" ;;
  audio/* | application/octet-stream) mediainfo "$1" || exit 1;;
  video/* )
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
    [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0 -c "jpeg" -q 3
    image "$CACHE" "$2" "$3" "$4" "$5"
    ;;
  */pdf)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}')"
    [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
    image "$CACHE.jpg" "$2" "$3" "$4" "$5"
    ;;
  *opendocument*) odt2txt "$1" ;;
  application/*officedocument*) pandoc "$1" -s -t markdown | bat -l markdown --terminal-width "$4" ;;
  application/pgp-encrypted) gpg -d -- "$1" ;;
esac
exit 1
