---
- name: Create the '$HOME/.config/waybar' directory if not exists
  ansible.builtin.file:
    path: "{{ home }}/.config/waybar"
    mode: u=rwx,g=,o=
    state: directory

- name: Copy waybar files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home }}/.config/waybar/{{ item }}"
    mode: u=rwx,g=,o=
    force: yes
  loop:
    - config
    - style.css
