#!/bin/bash

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_RIVER_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# dbus_launch="$( dbus-launch --sh-syntax )"
# eval "$dbus_launch"
# printf "%s" "$dbus_launch" > "$XDG_RUNTIME_DIR/dbus_launch"

RIVER_CONFIG="${RIVER_CONFIG:-${XDG_RIVER_CONFIG_HOME}/river}"
RIVER_RUNTIME="${RIVER_RUNTIME:-${XDG_RUNTIME_DIR}/river}"

mkdir -p "$RIVER_CONFIG"
mkdir -p "$RIVER_RUNTIME"


rm -f "${RIVER_RUNTIME}/tags"
rm -f "${RIVER_RUNTIME}/title"
rm -f "${RIVER_RUNTIME}/viewstag"

mkfifo "${RIVER_RUNTIME}/tag"
mkfifo "${RIVER_RUNTIME}/title"
mkfifo "${RIVER_RUNTIME}/viewstag"

# eval "${RIVER_CONFIG}/winitrc"

# create state change pipes and files
ristate -t -w -u | while IFS= read -r line; do
    printf "%s" "$line" | jq -rc ".tags.AUOptronics" | tr -d '["]' > "${RIVER_RUNTIME}/tags"
done &
ristate -t -w -u | while IFS= read -r line; do
    printf "%s" "$line" | jq -rc ".title" > "${RIVER_RUNTIME}/title"
done &
ristate -vt | while IFS= read -r line; do
    printf "%s\n" "$line" | jq -rc ".viewstag.AUOptronics?" | tr -d '["]' > "${RIVER_RUNTIME}/viewstag"
done &


ristate -t -w -u | while IFS= read -r line; do
    printf "%s" "$line" | jq -rc ".tags.AUOptronics" | tr -d '["]' > "${RIVER_RUNTIME}/current_tags"
done &
ristate -t -w -u | while IFS= read -r line; do
    printf "%s" "$line" | jq -rc ".title" > "${RIVER_RUNTIME}/current_title"
done &

# tail -f "${XDG_RUNTIME_DIR}/river/tag" | while IFS= read -r line; do
#     printf "%s" "$line" > "${RIVER_RUNTIME}/current_tag"
# done &
# tail -f "${XDG_RUNTIME_DIR}/river/title" | while IFS= read -r line; do
#     printf "%s" "$line" > "${RIVER_RUNTIME}/current_title"
# done &


# Set default options
riverctl background-color 0x000000
riverctl border-color-focused 0xff00ff
riverctl border-color-unfocused 0x000000
riverctl border-width 4
riverctl focus-follows-cursor disabled
riverctl hide-cursor 5000
riverctl hide-cursor-when-typing enabled
#riverctl keyboard-layout -options "caps:swapescape,altwin:prtsc_rwin" "gb"
riverctl keyboard-layout -options "altwin:prtsc_rwin" "gb"


# river rules
riverctl rule-add -app-id "mpv" tags "$(gettag "22")"
# riverctl rule-add float -app-id "searchmenu"
# riverctl rule-add no-float -app-id "term"
# riverctl rule-add no-float -app-id "term"

# NOTE: seperated repeatable config from init config
./river-config.sh

# Set keyboard repeat rate
riverctl set-repeat 50 300

# # Make certain views start floating
# riverctl float-filter-add app-id float
# riverctl float-filter-add title "popup title with spaces"
#
# # Set app-ids and titles of views which should use client side decorations
# riverctl csd-filter-add app-id "gedit"


# riverctl spawn "${XDG_CONFIG_HOME}/river/river_bar"
riverctl spawn "/usr/bin/waybar"
riverctl spawn "${XDG_CONFIG_HOME}/river/river_status"
riverctl spawn "${XDG_CONFIG_HOME}/river/river_acpi"

sh ${RIVER_CONFIG}/winitrc

riverctl spawn "wl-paste --type text --watch cliphist store"
riverctl spawn "wl-paste --type image --watch cliphist store"
riverctl spawn "wl-paste --type video --watch cliphist store"
riverctl spawn "wl-paste --type audio --watch cliphist store"
riverctl spawn "wl-paste --type application --watch cliphist store"

# riverctl spawn "~/.local/bin/lock"
# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout luatile


exec river-luatile
# exec rivertile -view-padding 6 -outer-padding 6

