#!/bin/bash

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_RIVER_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# dbus_launch="$( dbus-launch --sh-syntax )"
# eval "$dbus_launch"
# printf "%s" "$dbus_launch" > "$XDG_RUNTIME_DIR/dbus_launch"

RIVER_CONFIG="${RIVER_CONFIG:-${XDG_RIVER_CONFIG_HOME}/river}"
RIVER_RUNTIME="${RIVER_RUNTIME:-${XDG_RUNTIME_DIR}/river}"

mkdir -p "$RIVER_CONFIG"
mkdir -p "$RIVER_RUNTIME"


rm -f "${RIVER_RUNTIME}/tags"
rm -f "${RIVER_RUNTIME}/title"
rm -f "${RIVER_RUNTIME}/viewstag"

mkfifo "${RIVER_RUNTIME}/tag"
mkfifo "${RIVER_RUNTIME}/title"
mkfifo "${RIVER_RUNTIME}/viewstag"

# eval "${RIVER_CONFIG}/winitrc"

# create state change pipes and files
ristate -t -w -u | while IFS= read -r line; do
    printf "%s" "$line" | jq -rc ".tags.AUOptronics" | tr -d '["]' > "${RIVER_RUNTIME}/tags"
done &
ristate -t -w -u | while IFS= read -r line; do
    printf "%s" "$line" | jq -rc ".title" > "${RIVER_RUNTIME}/title"
done &
ristate -vt | while IFS= read -r line; do
    printf "%s\n" "$line" | jq -rc ".viewstag.AUOptronics?" | tr -d '["]' > "${RIVER_RUNTIME}/viewstag"
done &


ristate -t -w -u | while IFS= read -r line; do
    printf "%s" "$line" | jq -rc ".tags.AUOptronics" | tr -d '["]' > "${RIVER_RUNTIME}/current_tags"
done &
ristate -t -w -u | while IFS= read -r line; do
    printf "%s" "$line" | jq -rc ".title" > "${RIVER_RUNTIME}/current_title"
done &

# tail -f "${XDG_RUNTIME_DIR}/river/tag" | while IFS= read -r line; do
#     printf "%s" "$line" > "${RIVER_RUNTIME}/current_tag"
# done &
# tail -f "${XDG_RUNTIME_DIR}/river/title" | while IFS= read -r line; do
#     printf "%s" "$line" > "${RIVER_RUNTIME}/current_title"
# done &


# Set default options
riverctl background-color 0x000000
riverctl border-color-focused 0xff00ff
riverctl border-color-unfocused 0x000000
riverctl border-width 4
riverctl focus-follows-cursor disabled
riverctl hide-cursor 5000
riverctl hide-cursor-when-typing enabled
#riverctl keyboard-layout -options "caps:swapescape,altwin:prtsc_rwin" "gb"
riverctl keyboard-layout -options "altwin:prtsc_rwin" "gb"

# get tag value
gettag(){ eval "echo \$(( 1 << ($1 - 1) ))"; }
all_tags=4294967295
scratch_tag=$(( 1 << 32 ))

termcmd(){
    # printf "foot -a %s -T %s -w '%sx%s' -e %s" "$1" "$2" "${4:-700}" "${5:-500}" "$3"
    printf "foot -a %s -T %s -w '%sx%s' -e zsh -ic '%s'" "$1" "$2" "${4:-700}" "${5:-500}" "$3"
}

#define SCRATCHCMD(skey, class, title, cmd) { .v = (const char*[]){skey, "/bin/sh", "-c", TERMINAL " -c " class " -t " title " -e " cmd, NULL} }


# river rules
riverctl rule-add -app-id "mpv" tags "$(gettag "22")"
# riverctl rule-add float -app-id "searchmenu"
# riverctl rule-add no-float -app-id "term"
# riverctl rule-add no-float -app-id "term"

# Mod+Shift+Delete to exit river
riverctl map normal $mod+Shift Delete exit

#
# Basic window control and navigation
#

# Use the "logo" key as the primary modifier
mod="Mod4"

riverctl map normal $mod Q close    # close a window
# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod j focus-view next
riverctl map normal $mod k focus-view previous
riverctl map normal $mod l spawn "flow cycle-tags next"
riverctl map normal $mod h spawn "flow cycle-tags previous"

riverctl map normal $mod u toggle-focused-tags ${scratch_tag}
riverctl map normal $mod z spawn "wl-kbptr"

# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 32 ))

# Toggle the scratchpad with Super+P
riverctl map normal Super u toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad with Super+Shift+P
riverctl map normal Super+Shift u set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}


# insert mode
riverctl declare-mode insert
riverctl map normal $mod i enter-mode insert
riverctl map insert $mod escape enter-mode normal
riverctl map insert $mod bracketleft enter-mode normal
riverctl map insert $mod+Control bracketleft enter-mode normal


riverctl declare-mode output
riverctl map normal $mod o enter-mode output
riverctl map g $mod escape enter-mode normal
riverctl map g $mod bracketleft enter-mode normal
riverctl map g $mod+Control bracketleft enter-mode normal

# extra g mode
riverctl declare-mode g
riverctl map normal $mod g enter-mode g
riverctl map g $mod escape enter-mode normal
riverctl map g $mod bracketleft enter-mode normal
riverctl map g $mod+Control bracketleft enter-mode normal
riverctl map g $mod a spawn 'echo "audiebant" > "$XDG_RUNTIME_DIR/work_mode"'
riverctl map g $mod n spawn 'echo "normal" > "$XDG_RUNTIME_DIR/work_mode"'




# notifications
riverctl map normal $mod period spawn "dunstctl history-pop"
riverctl map normal $mod comma spawn "dunstctl close"
riverctl map normal $mod numbersign spawn "$( termcmd "fdunst" "fdunst" "fdunst" )"


# Mod+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal $mod Return spawn "/bin/foot -a 'term' /usr/bin/zsh"
riverctl map normal Control+Mod1 delete spawn "$( termcmd "powermenu" "Power" "powermenu" )"
riverctl map normal $mod X spawn "lock"

riverctl map normal $mod+Shift P spawn "$( termcmd "passmenu" "Pass" "PASS_FILTER='^x/.*$' pass menu" )"
riverctl map normal $mod+Alt P spawn "$( termcmd "passmenu" "Pass" "pass menu" )"
riverctl map normal $mod O spawn "$( termcmd "appmenu" "Apps" "appmenu" )"
riverctl map normal $mod C spawn "$( termcmd "clipmenu" "Clipboard" "fclip" )"
# riverctl map normal $mod S spawn "$( termcmd "fsearch" "Search" "fsearch" "3000" "100" )"
riverctl map normal $mod+Shift C spawn "$( termcmd "calc" "Calc" "qalc" )"
riverctl map normal $mod Y spawn "$( termcmd "ytdl" "ytdl" "ytdl -m" )"

riverctl map normal $mod N spawn "$( termcmd "nvimmail" "Mail" "nvim -c \"lua require([[notmuch]]).search_terms([[tag:inbox]])\"" )"
riverctl map normal $mod R spawn "$( termcmd "newsraft" "newsraft" "newsraft" )"
riverctl map normal $mod+Shift Return spawn "$( termcmd "lf" "lf" "lf" )"
riverctl map normal $mod T spawn "$( termcmd "bottom" "bottom" "btm -b" )"
riverctl map normal $mod+Shift T spawn "$( termcmd "bottom" "bottom" "btm" )"
riverctl map normal $mod M spawn "$( termcmd "netomutt" "mail" "netomutt" )"
riverctl map normal $mod P spawn "$( termcmd "pulsemixer" "pulsemixer" "pulsemixer" )"
riverctl map normal $mod+Shift y spawn "wl-paste | wtype -d 10 -"

# Screen shot
riverctl map normal $mod S spawn "shot"
riverctl map normal $mod+Shift S spawn "shot -s"


# Web Browser
riverctl map normal $mod w spawn www
riverctl declare-mode www
riverctl map normal $mod+Shift W enter-mode www
riverctl map normal $mod E enter-mode calendar
riverctl map www $mod x spawn "sh -c 'echo xxx > /tmp/qute.profile'; riverctl enter-mode normal"
riverctl map www $mod a spawn "sh -c 'echo alaska > /tmp/qute.profile'; riverctl enter-mode normal"
riverctl map www $mod escape enter-mode normal


# Calendar
riverctl declare-mode calendar
riverctl map normal $mod E enter-mode calendar
riverctl map calendar $mod escape enter-mode normal

calendar(){
    start="$( date -d "${2}/1" "+%d %b %Y" )"
    riverctl map calendar $mod $1 spawn "rem-calendar pdf ${start} $3 | zathura - & riverctl enter-mode normal"
}

calendar "E" "$( date "%b" )" "12"

for i in $(seq 1 12)
do
    calendar "F${i}" "${i}" "1"
done

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Ctrl L swap next
riverctl map normal $mod+Ctrl H swap previous
riverctl map normal $mod Tab focus-previous-tags
riverctl map normal $mod+Ctrl Tab send-to-previous-tags
riverctl map normal $mod BackSpace focus-previous-tags
riverctl map normal $mod+Ctrl BackSpace send-to-previous-tags

# # Mod+Period and Mod+Comma to focus the next/previous output
# riverctl map normal $mod Period focus-output next
# riverctl map normal $mod Comma focus-output previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift L focus-output next
riverctl map normal $mod+Shift H focus-output previous

# # Mod+Shift+{Period,Comma} to send the focused view to the next/previous output

riverctl map normal $mod+Shift+Alt L send-to-output next
riverctl map normal $mod+Shift+Alt H send-to-output previous

# # Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Z zoom

#brightness
riverctl declare-mode brightness
riverctl map normal $mod B enter-mode brightness
riverctl map brightness $mod escape enter-mode normal

brightness(){
    riverctl map brightness $mod $1 spawn "river-cmd brightness ${2}0"
}

for i in $(seq 1 9)
do
    brightness "$i" "$i"
done
brightness "0" "10"

# VOLUME

riverctl map normal $mod equal spawn 'river-cmd volume +5'
riverctl map normal $mod+Control equal spawn 'river-cmd volume +1'
riverctl map normal $mod+Shift equal spawn 'river-cmd volume +20'

riverctl map normal $mod minus spawn 'river-cmd volume -5'
riverctl map normal $mod+Control minus spawn 'river-cmd volume -1'
riverctl map normal $mod+Shift minus spawn 'river-cmd volume -20'
riverctl map normal $mod m spawn 'river-cmd volume mute'

#define VOLCMD(arg) SHCMD("/bin/pulsemixer " arg)
 #    { MODKEY,            -1,   XKB_KEY_equal,            spawn,          VOLCMD("--change-volume +5") },
 #    { MODKEY|CTRL,       -1,   XKB_KEY_equal,            spawn,          VOLCMD("--change-volume +1") },
 #    { MODKEY|SHIFT,      -1,   XKB_KEY_plus,             spawn,          VOLCMD("--change-volume +20") },
 #    { MODKEY,            -1,   XKB_KEY_minus,            spawn,          VOLCMD("--change-volume -5") },
 #    { MODKEY|CTRL,       -1,   XKB_KEY_minus,            spawn,          VOLCMD("--change-volume -1") },
 #    { MODKEY|SHIFT,      -1,   XKB_KEY_underscore,       spawn,          VOLCMD("--change-volume -20") },
	# { MODKEY,            -1,   XKB_KEY_m,                spawn,          VOLCMD("--toggle-mute") },

# # Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
# riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
# riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# # Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
# riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
# riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# # Mod+Alt+{H,J,K,L} to move views
# # riverctl map normal $mod+Mod1 H move left 100
# # riverctl map normal $mod+Mod1 J move down 100
# # riverctl map normal $mod+Mod1 K move up 100
# # riverctl map normal $mod+Mod1 L move right 100

# # Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
# riverctl map normal $mod+Mod1+Control H snap left
# riverctl map normal $mod+Mod1+Control J snap down
# riverctl map normal $mod+Mod1+Control K snap up
# riverctl map normal $mod+Mod1+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal $mod+Alt Left resize horizontal -100
riverctl map normal $mod+Alt Down resize vertical 100
riverctl map normal $mod+Alt Up resize vertical -100
riverctl map normal $mod+Alt Right resize horizontal 100

riverctl map normal $mod+Control Left move left 100
riverctl map normal $mod+Control Down move down 100
riverctl map normal $mod+Control Up move up 100
riverctl map normal $mod+Control Right move right 100

# # Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# # Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

tag() {
    key="$1"
    tag="$(gettag "$2")"

    # focus tag
    # riverctl map normal $mod $key spawn "river-cmd focus_tags '$2' '$tag'"
    riverctl map normal $mod $key spawn "flow toggle-tags '$tag'"
    # to tag focused view with tag
    riverctl map normal $mod+Shift $key set-view-tags $tag
    # toggle focus of tag
    riverctl map normal $mod+Control $key toggle-focused-tags $tag
    # toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $key toggle-view-tags $tag
}

set_tags(){
    for i in $(seq 1 9)
    do
        tag "$i" "$i"
    done

    tag "0" "10"

    for i in $(seq 1 12)
    do
        tag "F${i}" "$((${i} + 10))"
    done
}

set_tags

# Mod+a to focus all tags
# Mod+Shift+a to tag focused view with all tags
riverctl map normal $mod a set-focused-tags $all_tags
riverctl map normal $mod+Shift a set-view-tags $all_tags

# # Mod+Space to toggle float
riverctl map normal $mod+Shift Space toggle-float

# # Mod+F to toggle fullscreen
riverctl map normal $mod F send-layout-cmd luatile "toggle_monocle()"
riverctl map normal $mod+Shift F toggle-fullscreen
riverctl map normal $mod+Shift G send-layout-cmd luatile "toggle_gapt()"

# # Mod+{Up,Right,Down,Left} to change layout orientation
# riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
# riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
# riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
# riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

# # Declare a passthrough mode. This mode has only a single mapping to return to
# # normal mode. This makes it useful for testing a nested wayland compositor
# riverctl declare-mode passthrough

# # Mod+F11 to enter passthrough mode
# riverctl map normal $mod F11 enter-mode passthrough

# # Mod+F11 to return to normal mode
# riverctl map passthrough $mod F11 enter-mode normal

# # Various media key mapping examples for both normal and locked mode which do
# # not have a modifier
# for mode in normal locked
# do
#     # Eject the optical drive (well if you still have one that is)
#     riverctl map $mode None XF86Eject spawn 'eject -T'

#     # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
#     riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
#     riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
#     riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

#     # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
#     riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
#     riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
#     riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
#     riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

#     # Control screen backlight brighness with light (https://github.com/haikarainen/light)
#     riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
#     riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
# done


# Set keyboard repeat rate
riverctl set-repeat 50 300

# # Make certain views start floating
# riverctl float-filter-add app-id float
# riverctl float-filter-add title "popup title with spaces"
#
# # Set app-ids and titles of views which should use client side decorations
# riverctl csd-filter-add app-id "gedit"


# riverctl spawn "${XDG_CONFIG_HOME}/river/river_bar"
riverctl spawn "/usr/bin/waybar"
riverctl spawn "${XDG_CONFIG_HOME}/river/river_status"
riverctl spawn "${XDG_CONFIG_HOME}/river/river_acpi"

sh ${RIVER_CONFIG}/winitrc

riverctl spawn "wl-paste --type text --watch cliphist store"
riverctl spawn "wl-paste --type image --watch cliphist store"
riverctl spawn "wl-paste --type video --watch cliphist store"
riverctl spawn "wl-paste --type audio --watch cliphist store"
riverctl spawn "wl-paste --type application --watch cliphist store"

# riverctl spawn "~/.local/bin/lock"
# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout luatile


exec river-luatile
# exec rivertile -view-padding 6 -outer-padding 6

