---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ river_packages }}"

- name: Create the '$HOME/.config/river' directory if not exists
  ansible.builtin.file:
    path: "{{ home }}/.config/river"
    mode: u=rwx,g=,o=
    state: directory

- name: Copy river files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home }}/.config/river/{{ item }}"
    mode: u=rwx,g=,o=
    force: yes
  loop:
    - init
    - river-cmd
    - winitrc
    - river-config.sh
  notify: reload river
