---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ nvim_packages }}"

- name: Stash current changes if any
  command: git stash push -m "Stashed by ansible dotfiles"
  args:
    chdir: "{{ home }}/.config/nvim"
  register: stash_output
  failed_when: false
  changed_when: "'Saved working directory' in stash_output.stdout"

- name: Clone NeovimConfig into {{ home }}/.config/nvim
  git:
    repo: "git@github.com:simonhughxyz/NeovimConfig.git"
    dest: "{{ home }}/.config/nvim"
    version: "master"
    update: yes
    accept_hostkey: yes

- name: Ensure lua folder is deleted
  ansible.builtin.file:
    path: "{{ home }}/.config/nvim/lua"
    state: absent

- name: Tangle norg config
  command: "nvim -n --headless -c 'edit config.norg' -c 'Neorg tangle current-file' -c 'qa'"
  args:
    chdir: "{{ home }}/.config/nvim"

- name: Install lazy packages
  command: "nvim -n --headless -c 'Lazy install' -c 'qa'"

- name: Install treesitter parsers
  command: "nvim -n --headless -c 'TSUpdateSync' -c 'qa'"
