---
- name: Clone NeovimConfig into {{ home }}/.config/nvim
  git:
    repo: "git@github.com:simonhughxyz/NeovimConfig.git"
    dest: "{{ home }}/.config/nvim"
    version: "master"
    update: yes

- name: Tangle norg config
  command: "nvim -n --headless -c 'edit config.norg' -c 'Neorg tangle current-file' -c 'qa'"
  args:
    chdir: "{{ home }}/.config/nvim"

- name: Install lazy packages
  command: "nvim -n --headless -c 'Lazy install' -c 'qa'"

- name: Install treesitter parsers
  command: "nvim -n --headless -c 'TSUpdateSync' -c 'qa'"
